apiVersion: v2
name: gpkg-merger
description: A Helm chart for gpkg-merger service
type: application
version: 2.2.1
appVersion: 2.2.1
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
